# Generated by Django 6.0.6 on 2026-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MilitaryRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Назва"),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Скорочена назва"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Військове звання",
                "verbose_name_plural": "Військові звання",
                "db_table": "military_rank",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MilitarySpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код ВОС"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Військово-облікова спеціальність",
                "verbose_name_plural": "Військово-облікові спеціальності",
                "db_table": "military_specialty",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PersonnelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Назва"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Скорочена назва"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія особового складу",
                "verbose_name_plural": "Категорії особового складу",
                "db_table": "personnel_category",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TariffGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Тарифний розряд"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тарифний розряд",
                "verbose_name_plural": "Тарифні розряди",
                "db_table": "tariff_grade",
                "ordering": ("number",),
            },
        ),
    ]
