# Generated by Django 6.0.6 on 2026-07-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Повна назва"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Скорочена назва"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Наприклад: А1234",
                        max_length=30,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Організація",
                "verbose_name_plural": "Організації",
                "db_table": "organization",
                "ordering": ("short_name", "full_name"),
            },
        ),
        migrations.CreateModel(
            name="OrgUnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Назва"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Скорочена назва"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Тип підрозділу",
                "verbose_name_plural": "Типи підрозділів",
                "db_table": "org_unit_type",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300, verbose_name="Назва")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Скорочена назва"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Внутрішній код підрозділу (за наявності).",
                        max_length=30,
                        verbose_name="Код",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_units",
                        to="organization.organization",
                        verbose_name="Організація",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organization.orgunit",
                        verbose_name="Батьківський підрозділ",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_units",
                        to="organization.orgunittype",
                        verbose_name="Тип підрозділу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структурний підрозділ",
                "verbose_name_plural": "Структурні підрозділи",
                "db_table": "org_unit",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="StaffPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Назва посади"),
                ),
                (
                    "position_index",
                    models.PositiveIntegerField(verbose_name="№ за штатом"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Кількість штатних одиниць"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                (
                    "military_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.militaryrank",
                    ),
                ),
                (
                    "military_specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.militaryspecialty",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_positions",
                        to="organization.orgunit",
                        verbose_name="Підрозділ",
                    ),
                ),
                (
                    "personnel_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.personnelcategory",
                    ),
                ),
                (
                    "tariff_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.tariffgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штатна посада",
                "verbose_name_plural": "Штатні посади",
                "db_table": "staff_position",
                "ordering": ("org_unit", "position_index"),
            },
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "parent", "name"),
                name="uq_org_unit_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffposition",
            constraint=models.UniqueConstraint(
                fields=("org_unit", "position_index"), name="uq_staff_position_index"
            ),
        ),
    ]
