[project]
name = "personnel-system"
authors = [{ name = "sergbond", email = "" }]
license = "MIT"
version = "0.1.0"
requires-python = ">=3.13"
description = "Personnel management system"
readme = "README.md"
dependencies = [
    "black~=26.5.1",
    "django~=6.0.7",
    "django-cleanup>=9.0.0",
    "pillow~=12.3.0",
    "psycopg[binary]>=3.2,<4.0.0",
]


[dependency-groups]
dev = ["ruff~=0.15.21"]

[tool.ruff]
line-length = 79
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
